frontend:
  url: "http://localhost:10010"

util:
  path: "..//util"
spring:
  datasource:
    url: "jdbc:h2:mem:idekiller"
    generate-unique-name: false
    name: "idekiller"
    username: "sa"
    password: ""

  h2:
    console:
      enabled: true

